### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by antoniomo**
- Not trying to autodetect the command to use, as it is buggy
- Setting the command to use once
- log.Fatalf

### CODE REVIEW

**Comment by peteretelej** [comment]
How about, still auto-detecting the binary, but allowing and documenting in readme that the `-cmdDefault` can be specified (when specified, will not auto-detect)? This will allow both `nasa-wallpapers` and `nasa-wallpapers -cmdDefault gnome2` to work as intended. Most guys don't know the cmd they need to change the wallpaper, and auto-detection may work on most of their cases (while those that don't can still specify)

Other than that, lgtm

**Comment by peteretelej** [comment]
we could even run each auto-detected command, will fix bug of unused binaries, and work on the new ones.

**Comment by antoniomo** [comment]
> Most guys don't know the cmd they need to change the wallpaper, and auto-detection may work on most of their cases (while those that don't can still specify)

That's true, some people don't know that, and also auto-detection might work (and would be a great to have feature). My concern is that the order to detecting the binaries is arbitrary, and it's using/setting some "garbage" in config files or key-value stores that aren't used.

For example, say my system is mostly Gnome2 based, but I have some apps that use GTK3 and I have a `gsettings` binary. This will use it, and the command will probably "work" but the wallpaper won't be updated. Changing the slice order doesn't fix it neither as I can have a Gnome3 desktop and the command `gconftool-2` or `dconf` installed, or really any other on the list.

I think a better auto-detection could be done using the environment variables `XDG_CURRENT_DESKTOP` and `GDM_DESKTOP`. This way, if we _know_ which window manager is running, we can safely change the wallpaper. If this autodetection fails, we can just exit with a nice error message, asking the user to provide the `-cmd` flag. How does that sound?

**Comment by peteretelej** [comment]
Yea, detection via env variables would be best.  Though,  in case a user has multiple desktops they can still speficy which one to use e.g `-cmdDefault gnome2` and the auto detection will use that and skip the autodetection.  The autodetection in this case is just a fallback in case cmdDefault or cmd are not specified, and allows out of the box support  for most users with single desktop envs

**Comment by antoniomo** [comment]
Yeah that sounds good, I could give it a go during the week, but I won't have time for it today :)

**Pull request merged**
